# Generated by Django 2.2 on 2020-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.BigIntegerField()),
                ('membertypeid', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_question', models.CharField(blank=True, max_length=100, null=True)),
                ('challenge_answer', models.CharField(blank=True, max_length=100, null=True)),
                ('datedisabled', models.CharField(blank=True, max_length=255, null=True)),
                ('disabled', models.BooleanField(blank=True, null=True)),
                ('profiletype', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Member List',
                'db_table': 'members',
                'managed': False,
            },
        ),
    ]
